import streamlit as st
import pandas as pd
import numpy as np
import math
import io
import zipfile
import re
from datetime import datetime, timedelta

import plotly.express as px
import plotly.graph_objects as go

from sklearn.ensemble import IsolationForest, RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.cluster import DBSCAN


# ============================================================
# CASEFILE
# AI-Powered Missing Person Investigation
# and Location Prediction System
# ============================================================

st.set_page_config(
    page_title="CASEFILE | AI Investigation System",
    page_icon="🕵️",
    layout="wide",
    initial_sidebar_state="expanded"
)


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown("""
<style>

.main {
    background-color: #f7f8fa;
}

.block-container {
    padding-top: 1.5rem;
}

.case-header {
    padding: 25px;
    border-radius: 15px;
    background: linear-gradient(135deg, #111827, #263449);
    color: white;
    margin-bottom: 25px;
}

.case-header h1 {
    font-size: 42px;
    margin-bottom: 5px;
}

.case-header p {
    font-size: 17px;
    color: #d1d5db;
}

.metric-card {
    padding: 18px;
    border-radius: 12px;
    background: white;
    border: 1px solid #e5e7eb;
    text-align: center;
}

.warning-box {
    padding: 15px;
    border-radius: 10px;
    background: #fff7ed;
    border-left: 5px solid #f97316;
}

.success-box {
    padding: 15px;
    border-radius: 10px;
    background: #ecfdf5;
    border-left: 5px solid #10b981;
}

.info-box {
    padding: 15px;
    border-radius: 10px;
    background: #eff6ff;
    border-left: 5px solid #3b82f6;
}

</style>
""", unsafe_allow_html=True)


# ============================================================
# HEADER
# ============================================================

st.markdown("""
<div class="case-header">

<h1>🕵️ CASEFILE</h1>

<p>
AI-Powered Missing Person Investigation and Location Prediction System
</p>

<p>
Advanced ML • Anomaly Detection • Location Prediction • Route Analysis •
Geospatial Intelligence • Explainable AI
</p>

</div>
""", unsafe_allow_html=True)


# ============================================================
# DISCLAIMER
# ============================================================

st.warning(
    "⚠️ INVESTIGATION-SUPPORT PROTOTYPE: "
    "Predictions generated by this application are probabilistic estimates "
    "for research/academic purposes. They must not be treated as proof of "
    "a person's location, identity, guilt, or innocence. Real investigations "
    "require qualified investigators, verified evidence, and lawful procedures."
)


# ============================================================
# UTILITY FUNCTIONS
# ============================================================

def haversine(lat1, lon1, lat2, lon2):
    """
    Calculate distance between two GPS coordinates in kilometers.
    """

    R = 6371.0

    lat1 = np.radians(lat1)
    lat2 = np.radians(lat2)

    dlat = np.radians(lat2 - lat1)
    dlon = np.radians(lon2 - lon1)

    a = (
        np.sin(dlat / 2) ** 2
        + np.cos(lat1)
        * np.cos(lat2)
        * np.sin(dlon / 2) ** 2
    )

    return 2 * R * np.arcsin(np.sqrt(a))


def bearing(lat1, lon1, lat2, lon2):
    """
    Calculate movement direction.
    """

    lat1 = np.radians(lat1)
    lat2 = np.radians(lat2)

    dlon = np.radians(lon2 - lon1)

    x = np.sin(dlon) * np.cos(lat2)

    y = (
        np.cos(lat1) * np.sin(lat2)
        - np.sin(lat1) * np.cos(lat2) * np.cos(dlon)
    )

    angle = np.degrees(np.arctan2(x, y))

    return (angle + 360) % 360


def generate_demo_data(n=2500):
    """
    Generate realistic synthetic trajectory data.

    Used when no GeoLife dataset is supplied.
    """

    np.random.seed(42)

    start_lat = 23.2599
    start_lon = 77.4126

    timestamps = []
    latitudes = []
    longitudes = []

    current_lat = start_lat
    current_lon = start_lon

    current_time = datetime(2026, 1, 1, 8, 0, 0)

    for i in range(n):

        timestamps.append(current_time)

        # Random movement
        movement_lat = np.random.normal(0, 0.0008)
        movement_lon = np.random.normal(0, 0.0008)

        current_lat += movement_lat
        current_lon += movement_lon

        latitudes.append(current_lat)
        longitudes.append(current_lon)

        current_time += timedelta(minutes=5)

    df = pd.DataFrame({
        "timestamp": timestamps,
        "latitude": latitudes,
        "longitude": longitudes
    })

    return df


def clean_gps_data(df):
    """
    Standardize GPS dataframe.
    """

    df = df.copy()

    # Lowercase columns
    df.columns = [
        str(c).strip().lower().replace(" ", "_")
        for c in df.columns
    ]

    # Detect latitude
    lat_candidates = [
        "latitude",
        "lat",
        "gps_latitude",
        "y"
    ]

    lon_candidates = [
        "longitude",
        "lon",
        "lng",
        "gps_longitude",
        "x"
    ]

    time_candidates = [
        "timestamp",
        "datetime",
        "date_time",
        "date",
        "time"
    ]

    lat_col = None
    lon_col = None
    time_col = None

    for c in lat_candidates:
        if c in df.columns:
            lat_col = c
            break

    for c in lon_candidates:
        if c in df.columns:
            lon_col = c
            break

    for c in time_candidates:
        if c in df.columns:
            time_col = c
            break

    # GeoLife special format
    if lat_col is None or lon_col is None:

        numeric_cols = []

        for col in df.columns:

            converted = pd.to_numeric(
                df[col],
                errors="coerce"
            )

            if converted.notna().sum() > len(df) * 0.5:
                numeric_cols.append(col)

        if len(numeric_cols) >= 2:

            possible = []

            for col in numeric_cols:

                values = pd.to_numeric(
                    df[col],
                    errors="coerce"
                )

                if values.between(-90, 90).mean() > 0.8:
                    possible.append(col)

            if len(possible) >= 2:
                lat_col = possible[0]
                lon_col = possible[1]

    if lat_col is None or lon_col is None:
        raise ValueError(
            "Could not identify latitude and longitude columns."
        )

    df["latitude"] = pd.to_numeric(
        df[lat_col],
        errors="coerce"
    )

    df["longitude"] = pd.to_numeric(
        df[lon_col],
        errors="coerce"
    )

    # Timestamp
    if time_col is not None:

        df["timestamp"] = pd.to_datetime(
            df[time_col],
            errors="coerce"
        )

    else:

        # Generate artificial timestamps
        df["timestamp"] = pd.date_range(
            start="2026-01-01",
            periods=len(df),
            freq="5min"
        )

    df = df[
        [
            "timestamp",
            "latitude",
            "longitude"
        ]
    ]

    df = df.dropna()

    df = df[
        df["latitude"].between(-90, 90)
        & df["longitude"].between(-180, 180)
    ]

    df = df.sort_values("timestamp")

    df = df.drop_duplicates()

    df = df.reset_index(drop=True)

    return df


def read_csv_from_zip(uploaded_file):
    """
    Try to read GPS files from GeoLife ZIP.
    """

    records = []

    with zipfile.ZipFile(uploaded_file) as z:

        names = z.namelist()

        for name in names:

            lower = name.lower()

            if not lower.endswith(".plt"):
                continue

            try:

                with z.open(name) as f:

                    raw = f.read()

                text = raw.decode(
                    "utf-8",
                    errors="ignore"
                )

                rows = []

                for line in text.splitlines():

                    parts = line.strip().split(",")

                    if len(parts) >= 6:

                        try:

                            lat = float(parts[0])
                            lon = float(parts[1])

                            date = parts[5]
                            time_value = (
                                parts[6]
                                if len(parts) > 6
                                else "00:00:00"
                            )

                            timestamp = pd.to_datetime(
                                date + " " + time_value,
                                errors="coerce"
                            )

                            rows.append(
                                [
                                    timestamp,
                                    lat,
                                    lon
                                ]
                            )

                        except Exception:
                            continue

                if rows:

                    temp = pd.DataFrame(
                        rows,
                        columns=[
                            "timestamp",
                            "latitude",
                            "longitude"
                        ]
                    )

                    records.append(temp)

            except Exception:
                continue

    if not records:
        return None

    df = pd.concat(
        records,
        ignore_index=True
    )

    return df


# ============================================================
# FEATURE ENGINEERING
# ============================================================

def create_features(df):

    data = df.copy()

    data["timestamp"] = pd.to_datetime(
        data["timestamp"],
        errors="coerce"
    )

    data = data.dropna()

    data["hour"] = data["timestamp"].dt.hour

    data["day_of_week"] = (
        data["timestamp"].dt.dayofweek
    )

    data["is_weekend"] = (
        data["day_of_week"] >= 5
    ).astype(int)

    data["prev_lat"] = (
        data["latitude"].shift(1)
    )

    data["prev_lon"] = (
        data["longitude"].shift(1)
    )

    data["distance_km"] = haversine(
        data["prev_lat"],
        data["prev_lon"],
        data["latitude"],
        data["longitude"]
    )

    data["distance_km"] = (
        data["distance_km"]
        .fillna(0)
    )

    time_diff = (
        data["timestamp"]
        .diff()
        .dt.total_seconds()
        / 3600
    )

    data["time_diff_hours"] = (
        time_diff
        .replace(0, np.nan)
        .fillna(0.0833)
    )

    data["speed_kmh"] = (
        data["distance_km"]
        / data["time_diff_hours"]
    )

    data["speed_kmh"] = (
        data["speed_kmh"]
        .replace(
            [np.inf, -np.inf],
            np.nan
        )
        .fillna(0)
        .clip(0, 200)
    )

    data["bearing"] = bearing(
        data["prev_lat"].fillna(
            data["latitude"]
        ),
        data["prev_lon"].fillna(
            data["longitude"]
        ),
        data["latitude"],
        data["longitude"]
    )

    data["rolling_speed"] = (
        data["speed_kmh"]
        .rolling(10)
        .mean()
        .fillna(data["speed_kmh"])
    )

    data["rolling_distance"] = (
        data["distance_km"]
        .rolling(10)
        .sum()
        .fillna(data["distance_km"])
    )

    data = data.replace(
        [np.inf, -np.inf],
        np.nan
    )

    data = data.dropna()

    return data.reset_index(drop=True)


# ============================================================
# ANOMALY DETECTION
# ============================================================

def detect_anomalies(df, contamination=0.03):

    data = df.copy()

    features = [
        "latitude",
        "longitude",
        "speed_kmh",
        "distance_km",
        "hour",
        "bearing"
    ]

    X = data[features].replace(
        [np.inf, -np.inf],
        np.nan
    ).fillna(0)

    scaler = StandardScaler()

    X_scaled = scaler.fit_transform(X)

    model = IsolationForest(
        n_estimators=150,
        contamination=contamination,
        random_state=42
    )

    predictions = model.fit_predict(
        X_scaled
    )

    scores = model.decision_function(
        X_scaled
    )

    data["anomaly"] = (
        predictions == -1
    )

    data["anomaly_score"] = -scores

    # Normalize score
    min_score = data["anomaly_score"].min()
    max_score = data["anomaly_score"].max()

    if max_score != min_score:

        data["anomaly_probability"] = (
            (
                data["anomaly_score"]
                - min_score
            )
            /
            (
                max_score
                - min_score
            )
        )

    else:

        data["anomaly_probability"] = 0.0

    return data, model


# ============================================================
# LOCATION PREDICTION
# ============================================================

def train_location_model(df):

    data = df.copy()

    data["target_lat"] = (
        data["latitude"].shift(-1)
    )

    data["target_lon"] = (
        data["longitude"].shift(-1)
    )

    data = data.dropna()

    features = [
        "latitude",
        "longitude",
        "hour",
        "day_of_week",
        "speed_kmh",
        "bearing",
        "rolling_speed"
    ]

    X = data[features]

    y_lat = data["target_lat"]

    y_lon = data["target_lon"]

    # Keep training reasonably fast for Streamlit
    max_samples = 12000

    if len(X) > max_samples:

        sample_indices = np.linspace(
            0,
            len(X) - 1,
            max_samples
        ).astype(int)

        X = X.iloc[sample_indices]

        y_lat = y_lat.iloc[sample_indices]

        y_lon = y_lon.iloc[sample_indices]

    model_lat = RandomForestRegressor(
        n_estimators=80,
        max_depth=15,
        random_state=42,
        n_jobs=-1
    )

    model_lon = RandomForestRegressor(
        n_estimators=80,
        max_depth=15,
        random_state=42,
        n_jobs=-1
    )

    model_lat.fit(
        X,
        y_lat
    )

    model_lon.fit(
        X,
        y_lon
    )

    return (
        model_lat,
        model_lon,
        features
    )


def predict_next_location(
    df,
    model_lat,
    model_lon,
    features
):

    latest = df.iloc[-1]

    X = pd.DataFrame(
        [[
            latest["latitude"],
            latest["longitude"],
            latest["hour"],
            latest["day_of_week"],
            latest["speed_kmh"],
            latest["bearing"],
            latest["rolling_speed"]
        ]],
        columns=features
    )

    predicted_lat = model_lat.predict(X)[0]

    predicted_lon = model_lon.predict(X)[0]

    return predicted_lat, predicted_lon


# ============================================================
# SEARCH AREA GENERATION
# ============================================================

def generate_search_areas(
    predicted_lat,
    predicted_lon,
    radius_km=2.0
):

    # Approximate degree conversion
    lat_degree = radius_km / 111

    lon_degree = (
        radius_km
        /
        (
            111
            *
            max(
                math.cos(
                    math.radians(
                        predicted_lat
                    )
                ),
                0.1
            )
        )
    )

    offsets = [
        (0, 0),
        (0.5, 0.5),
        (0.5, -0.5),
        (-0.5, 0.5),
        (-0.5, -0.5),
        (1, 0),
        (-1, 0),
        (0, 1),
        (0, -1)
    ]

    results = []

    for i, (x, y) in enumerate(offsets):

        lat = (
            predicted_lat
            + x * lat_degree
        )

        lon = (
            predicted_lon
            + y * lon_degree
        )

        # Center receives highest ranking
        score = 100 - (
            abs(x) + abs(y)
        ) * 15

        results.append({
            "Area": f"Search Zone {i + 1}",
            "Latitude": lat,
            "Longitude": lon,
            "Priority Score": max(
                10,
                round(score, 2)
            )
        })

    return pd.DataFrame(results).sort_values(
        "Priority Score",
        ascending=False
    )


# ============================================================
# ROUTE PREDICTION
# ============================================================

def generate_predicted_route(
    current_lat,
    current_lon,
    predicted_lat,
    predicted_lon,
    steps=20
):

    lats = np.linspace(
        current_lat,
        predicted_lat,
        steps
    )

    lons = np.linspace(
        current_lon,
        predicted_lon,
        steps
    )

    route = pd.DataFrame({
        "latitude": lats,
        "longitude": lons
    })

    return route


# ============================================================
# EXPLAINABILITY
# ============================================================

def explain_prediction(df):

    latest = df.iloc[-1]

    explanations = []

    if latest["speed_kmh"] < 5:

        explanations.append(
            "Low recent movement speed"
        )

    elif latest["speed_kmh"] < 30:

        explanations.append(
            "Movement speed is within a typical local travel range"
        )

    else:

        explanations.append(
            "Recent movement speed is relatively high"
        )

    if latest["hour"] >= 22 or latest["hour"] <= 5:

        explanations.append(
            "The latest movement occurred during nighttime hours"
        )

    if latest["rolling_speed"] > 40:

        explanations.append(
            "Recent trajectory contains sustained movement"
        )

    else:

        explanations.append(
            "Recent trajectory indicates relatively slow movement"
        )

    if latest["anomaly"]:

        explanations.append(
            "The latest movement was identified as anomalous"
        )

    else:

        explanations.append(
            "The latest movement does not appear strongly anomalous"
        )

    return explanations


# ============================================================
# DATA LOADING
# ============================================================

@st.cache_data(show_spinner=False)
def load_uploaded_data(file_bytes, file_name):

    if file_name.lower().endswith(".zip"):

        file_object = io.BytesIO(file_bytes)

        df = read_csv_from_zip(
            file_object
        )

        if df is None:
            raise ValueError(
                "No valid GeoLife .plt GPS files were found."
            )

    elif file_name.lower().endswith(".csv"):

        df = pd.read_csv(
            io.BytesIO(file_bytes)
        )

        df = clean_gps_data(df)

    else:

        raise ValueError(
            "Please upload a CSV or GeoLife ZIP file."
        )

    return df


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("🔧 CASEFILE Controls")

st.sidebar.markdown(
    "### 1. Data Source"
)

uploaded_file = st.sidebar.file_uploader(
    "Upload GeoLife ZIP or GPS CSV",
    type=["zip", "csv"]
)

use_demo = st.sidebar.checkbox(
    "Use demonstration data",
    value=True
)

st.sidebar.markdown(
    "---"
)

st.sidebar.markdown(
    "### 2. Model Settings"
)

contamination = st.sidebar.slider(
    "Anomaly sensitivity",
    min_value=0.01,
    max_value=0.15,
    value=0.03,
    step=0.01
)

search_radius = st.sidebar.slider(
    "Search radius (km)",
    min_value=0.5,
    max_value=10.0,
    value=2.0,
    step=0.5
)

st.sidebar.markdown(
    "---"
)

st.sidebar.info(
    "CASEFILE is an academic investigation-support "
    "prototype. It does not determine the actual location "
    "of a missing person."
)


# ============================================================
# LOAD DATA
# ============================================================

if uploaded_file is not None:

    try:

        with st.spinner(
            "Reading GPS dataset..."
        ):

            raw_df = load_uploaded_data(
                uploaded_file.getvalue(),
                uploaded_file.name
            )

        st.success(
            f"Loaded {len(raw_df):,} GPS records."
        )

    except Exception as e:

        st.error(
            f"Dataset error: {e}"
        )

        st.info(
            "The application will use demonstration data instead."
        )

        raw_df = generate_demo_data()

elif use_demo:

    raw_df = generate_demo_data()

else:

    st.info(
        "Upload a dataset or enable demonstration data."
    )

    st.stop()


# ============================================================
# LIMIT DATA FOR WEB APP
# ============================================================

if len(raw_df) > 50000:

    raw_df = raw_df.tail(50000).copy()

    st.info(
        "Large dataset detected. The latest 50,000 records "
        "are used to keep the dashboard responsive."
    )


# ============================================================
# CREATE FEATURES
# ============================================================

with st.spinner(
    "Preparing movement intelligence..."
):

    data = clean_gps_data(
        raw_df
    )

    data = create_features(
        data
    )


# ============================================================
# RUN ANOMALY DETECTION
# ============================================================

with st.spinner(
    "Running anomaly detection..."
):

    data, anomaly_model = detect_anomalies(
        data,
        contamination
    )


# ============================================================
# TRAIN LOCATION MODEL
# ============================================================

with st.spinner(
    "Training location prediction model..."
):

    model_lat, model_lon, feature_columns = (
        train_location_model(data)
    )


# ============================================================
# PREDICT LOCATION
# ============================================================

pred_lat, pred_lon = predict_next_location(
    data,
    model_lat,
    model_lon,
    feature_columns
)

# Last known point
last_lat = data.iloc[-1]["latitude"]
last_lon = data.iloc[-1]["longitude"]


# ============================================================
# SEARCH AREAS
# ============================================================

search_areas = generate_search_areas(
    pred_lat,
    pred_lon,
    search_radius
)


# ============================================================
# PREDICTED ROUTE
# ============================================================

route = generate_predicted_route(
    last_lat,
    last_lon,
    pred_lat,
    pred_lon
)


# ============================================================
# EXPLANATION
# ============================================================

explanation = explain_prediction(
    data
)


# ============================================================
# DASHBOARD METRICS
# ============================================================

st.subheader(
    "📊 Investigation Overview"
)

col1, col2, col3, col4, col5 = st.columns(5)

with col1:

    st.metric(
        "GPS Records",
        f"{len(data):,}"
    )

with col2:

    st.metric(
        "Anomalies",
        f"{int(data['anomaly'].sum()):,}"
    )

with col3:

    st.metric(
        "Avg Speed",
        f"{data['speed_kmh'].mean():.1f} km/h"
    )

with col4:

    st.metric(
        "Last Latitude",
        f"{last_lat:.5f}"
    )

with col5:

    st.metric(
        "Last Longitude",
        f"{last_lon:.5f}"
    )


# ============================================================
# TABS
# ============================================================

tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs(
    [
        "🗺️ Investigation Map",
        "📍 Location Prediction",
        "🚨 Anomaly Detection",
        "🛣️ Route Analysis",
        "🧠 Explainable AI",
        "📈 Analytics"
    ]
)


# ============================================================
# TAB 1 — MAP
# ============================================================

with tab1:

    st.subheader(
        "🗺️ AI Investigation Map"
    )

    st.caption(
        "Blue = observed trajectory | "
        "Red = predicted location | "
        "Orange = anomalous movement"
    )

    # Sample for performance
    plot_data = data.copy()

    if len(plot_data) > 5000:

        plot_data = plot_data.sample(
            5000,
            random_state=42
        )

    fig = go.Figure()

    # Observed trajectory
    fig.add_trace(
        go.Scattermap(
            lat=data["latitude"],
            lon=data["longitude"],
            mode="lines",
            name="Observed Trajectory",
            line=dict(width=3)
        )
    )

    # Anomalies
    anomalies = data[
        data["anomaly"]
    ]

    if len(anomalies) > 0:

        if len(anomalies) > 1000:

            anomalies = anomalies.tail(
                1000
            )

        fig.add_trace(
            go.Scattermap(
                lat=anomalies["latitude"],
                lon=anomalies["longitude"],
                mode="markers",
                name="Anomalies",
                marker=dict(
                    size=9
                )
            )
        )

    # Predicted location
    fig.add_trace(
        go.Scattermap(
            lat=[pred_lat],
            lon=[pred_lon],
            mode="markers",
            name="Predicted Location",
            marker=dict(
                size=18
            )
        )
    )

    # Last known location
    fig.add_trace(
        go.Scattermap(
            lat=[last_lat],
            lon=[last_lon],
            mode="markers",
            name="Last Known Location",
            marker=dict(
                size=14
            )
        )
    )

    fig.update_layout(
        map=dict(
            style="open-street-map",
            center=dict(
                lat=float(last_lat),
                lon=float(last_lon)
            ),
            zoom=11
        ),
        height=650,
        margin=dict(
            l=0,
            r=0,
            t=0,
            b=0
        ),
        legend=dict(
            orientation="h"
        )
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )


# ============================================================
# TAB 2 — LOCATION PREDICTION
# ============================================================

with tab2:

    st.subheader(
        "📍 Probable Next Location"
    )

    c1, c2, c3 = st.columns(3)

    with c1:

        st.metric(
            "Predicted Latitude",
            f"{pred_lat:.6f}"
        )

    with c2:

        st.metric(
            "Predicted Longitude",
            f"{pred_lon:.6f}"
        )

    with c3:

        distance = haversine(
            last_lat,
            last_lon,
            pred_lat,
            pred_lon
        )

        st.metric(
            "Distance from Last Point",
            f"{float(distance):.2f} km"
        )

    st.markdown(
        """
        <div class="warning-box">

        <b>Interpretation:</b><br>
        The coordinates shown above represent a machine-learning
        estimate of the next probable trajectory point based on
        historical movement patterns.

        This is <b>not</b> a confirmed location.

        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("### 🔎 Ranked Search Areas")

    display_areas = search_areas.copy()

    display_areas["Latitude"] = (
        display_areas["Latitude"].round(6)
    )

    display_areas["Longitude"] = (
        display_areas["Longitude"].round(6)
    )

    st.dataframe(
        display_areas,
        use_container_width=True,
        hide_index=True
    )


# ============================================================
# TAB 3 — ANOMALY
# ============================================================

with tab3:

    st.subheader(
        "🚨 Movement Anomaly Detection"
    )

    st.write(
        "Isolation Forest is used to identify movement "
        "patterns that differ from the learned trajectory."
    )

    anomaly_count = int(
        data["anomaly"].sum()
    )

    total = len(data)

    anomaly_percent = (
        anomaly_count / total * 100
        if total > 0
        else 0
    )

    c1, c2 = st.columns(2)

    with c1:

        st.metric(
            "Detected Anomalies",
            anomaly_count
        )

    with c2:

        st.metric(
            "Anomaly Percentage",
            f"{anomaly_percent:.2f}%"
        )

    fig = px.scatter(
        data.tail(3000),
        x="timestamp",
        y="speed_kmh",
        color="anomaly",
        title="Movement Speed and Anomalies"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    st.write(
        "### Latest Anomalous Records"
    )

    st.dataframe(
        data[
            data["anomaly"]
        ]
        .sort_values(
            "anomaly_probability",
            ascending=False
        )
        .head(50)[
            [
                "timestamp",
                "latitude",
                "longitude",
                "speed_kmh",
                "anomaly_probability"
            ]
        ],
        use_container_width=True,
        hide_index=True
    )


# ============================================================
# TAB 4 — ROUTE ANALYSIS
# ============================================================

with tab4:

    st.subheader(
        "🛣️ Predicted Route"
    )

    st.write(
        "The route shown below is an interpolated probable "
        "trajectory between the last observed point and the "
        "model's predicted next location."
    )

    route_fig = go.Figure()

    route_fig.add_trace(
        go.Scattermap(
            lat=data["latitude"],
            lon=data["longitude"],
            mode="lines",
            name="Historical Route"
        )
    )

    route_fig.add_trace(
        go.Scattermap(
            lat=route["latitude"],
            lon=route["longitude"],
            mode="lines+markers",
            name="Predicted Route",
            marker=dict(
                size=6
            )
        )
    )

    route_fig.add_trace(
        go.Scattermap(
            lat=[pred_lat],
            lon=[pred_lon],
            mode="markers",
            name="Predicted Destination",
            marker=dict(
                size=18
            )
        )
    )

    route_fig.update_layout(
        map=dict(
            style="open-street-map",
            center=dict(
                lat=float(last_lat),
                lon=float(last_lon)
            ),
            zoom=11
        ),
        height=600,
        margin=dict(
            l=0,
            r=0,
            t=0,
            b=0
        )
    )

    st.plotly_chart(
        route_fig,
        use_container_width=True
    )

    st.write(
        "### Predicted Route Coordinates"
    )

    st.dataframe(
        route.round(6),
        use_container_width=True,
        hide_index=True
    )


# ============================================================
# TAB 5 — EXPLAINABLE AI
# ============================================================

with tab5:

    st.subheader(
        "🧠 Explainable AI"
    )

    st.write(
        "The system provides human-readable factors that "
        "describe why the current movement pattern influenced "
        "the prediction."
    )

    for item in explanation:

        st.markdown(
            f"""
            <div class="info-box">
            🔹 {item}
            </div>
            """,
            unsafe_allow_html=True
        )

    st.write(
        "### Important Model Factors"
    )

    importance_features = [
        "latitude",
        "longitude",
        "hour",
        "day_of_week",
        "speed_kmh",
        "bearing",
        "rolling_speed"
    ]

    importances = (
        model_lat.feature_importances_
    )

    importance_df = pd.DataFrame({
        "Feature": importance_features,
        "Importance": importances
    }).sort_values(
        "Importance",
        ascending=False
    )

    fig = px.bar(
        importance_df,
        x="Importance",
        y="Feature",
        orientation="h",
        title="Location Prediction Feature Importance"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )


# ============================================================
# TAB 6 — ANALYTICS
# ============================================================

with tab6:

    st.subheader(
        "📈 Movement Analytics"
    )

    col1, col2 = st.columns(2)

    with col1:

        speed_fig = px.histogram(
            data,
            x="speed_kmh",
            nbins=50,
            title="Speed Distribution"
        )

        st.plotly_chart(
            speed_fig,
            use_container_width=True
        )

    with col2:

        hourly = (
            data
            .groupby("hour")
            .size()
            .reset_index(
                name="records"
            )
        )

        hour_fig = px.bar(
            hourly,
            x="hour",
            y="records",
            title="Movement by Hour"
        )

        st.plotly_chart(
            hour_fig,
            use_container_width=True
        )

    distance_fig = px.line(
        data.tail(2000),
        x="timestamp",
        y="distance_km",
        title="Movement Distance Over Time"
    )

    st.plotly_chart(
        distance_fig,
        use_container_width=True
    )


# ============================================================
# DOWNLOAD RESULTS
# ============================================================

st.markdown("---")

st.subheader(
    "📥 Export Investigation Results"
)

export_df = data[
    [
        "timestamp",
        "latitude",
        "longitude",
        "speed_kmh",
        "distance_km",
        "bearing",
        "anomaly",
        "anomaly_probability"
    ]
].copy()

csv = export_df.to_csv(
    index=False
).encode("utf-8")

st.download_button(
    label="⬇️ Download Movement Analysis CSV",
    data=csv,
    file_name="casefile_movement_analysis.csv",
    mime="text/csv"
)


# ============================================================
# FOOTER
# ============================================================

st.markdown("---")

st.markdown(
    """
    <div style="text-align:center;color:#6b7280">

    <b>CASEFILE</b><br>

    AI-Powered Missing Person Investigation and
    Location Prediction System<br><br>

    Academic / Research Prototype •
    Probabilistic Predictions Only

    </div>
    """,
    unsafe_allow_html=True
)
